# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reasearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weekday', models.IntegerField(default=4)),
                ('month', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Reasearch_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberin', models.IntegerField()),
                ('numberout', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('reasearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Reasearch')),
            ],
        ),
        migrations.CreateModel(
            name='Reasearcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReasearchStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weekday', models.IntegerField(default=4)),
                ('month', models.IntegerField(default=4)),
                ('reasearcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Reasearcher')),
            ],
        ),
        migrations.CreateModel(
            name='ReasearchStand_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbercome', models.IntegerField()),
                ('timewait', models.IntegerField()),
                ('reasearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Reasearch')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('W', 'Winter'), ('S', 'Summer'), ('A', 'Autumn'), ('Sp', 'Spring')], max_length=2)),
                ('daytype', models.CharField(choices=[('W', 'Workday'), ('F', 'Friday'), ('O', 'Day Out')], max_length=1)),
                ('timestart', models.TimeField()),
                ('timeend', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('route', models.ManyToManyField(to='transportapp.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Transpor_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('maxpeople', models.IntegerField(default=50)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Transpor_Type'),
        ),
        migrations.AddField(
            model_name='result',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Route'),
        ),
        migrations.AddField(
            model_name='reasearchstand_detail',
            name='traffic_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Traffic_Stop'),
        ),
        migrations.AddField(
            model_name='reasearchstand',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Route'),
        ),
        migrations.AddField(
            model_name='reasearch_detail',
            name='traffic_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Traffic_Stop'),
        ),
        migrations.AddField(
            model_name='reasearch',
            name='reasearcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Reasearcher'),
        ),
        migrations.AddField(
            model_name='reasearch',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Route'),
        ),
    ]
