# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reasearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Day_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Reasearch_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Reasearch')),
            ],
        ),
        migrations.CreateModel(
            name='Reasearcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Day_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Time_of_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('route', models.ManyToManyField(to='transportapp.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Transpor_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Transpor_Type'),
        ),
        migrations.AddField(
            model_name='result',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Route'),
        ),
        migrations.AddField(
            model_name='result',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Season'),
        ),
        migrations.AddField(
            model_name='result',
            name='time_of_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Time_of_Day'),
        ),
        migrations.AddField(
            model_name='result',
            name='traffic_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Traffic_Stop'),
        ),
        migrations.AddField(
            model_name='reasearch_detail',
            name='time_of_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Time_of_Day'),
        ),
        migrations.AddField(
            model_name='reasearch_detail',
            name='traffic_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Traffic_Stop'),
        ),
        migrations.AddField(
            model_name='reasearch',
            name='reasearcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Reasearcher'),
        ),
        migrations.AddField(
            model_name='reasearch',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Route'),
        ),
        migrations.AddField(
            model_name='reasearch',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Season'),
        ),
    ]
