# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('W', 'Winter'), ('S', 'Summer'), ('A', 'Autumn'), ('Sp', 'Spring')], max_length=2)),
                ('daytype', models.CharField(choices=[('W', 'Workday'), ('F', 'Friday'), ('O', 'Day Out')], max_length=1)),
                ('timestart', models.TimeField()),
                ('timeend', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.Route')),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='route',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
