# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0002_auto_20170421_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasearch',
            name='weekday',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='reasearchstand',
            name='weekday',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='reasearchstand_detail',
            name='reasearch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportapp.ReasearchStand'),
        ),
    ]
