# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0003_auto_20170423_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasearch',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reasearchstand',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
