# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0004_auto_20170423_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reasearch',
            name='reasearcher',
        ),
        migrations.RemoveField(
            model_name='reasearchstand',
            name='reasearcher',
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='month',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='weekday',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reasearchstand',
            name='month',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='reasearchstand',
            name='weekday',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Reasearcher',
        ),
    ]
